### ISSUE TITLE
Práctica terminada

### ISSUE THREAD

**Issue by ShayBRJ** [ULL-ESIT-DMSI-2324/intro2sd-borja-medina-ramos-alu0101337609#13]
Se ha completado la práctica correspondiente (*Introducción al Desarrollo de Sistemas*)
Saludos @crguezl 👍

**Comment by crguezl** [comment]
@ShayBRJ 

Te ha quedado un estupendo sitio web.

Recuerda que para terminar debes añadir el JSON sobre este mismo repo y visualizarlo en el post de informe.

**Comment by ShayBRJ** [comment]
@crguezl 
Se han incluido los cambios comentados en clase así como la actualización del README.md incluyendo los mismos.
Saludos 😄
